### ISSUE TITLE
CPU power issue?

### ISSUE THREAD

**Issue by Efrtlessent** [Lauriethefish/QuestPatcher#103]
I have an i3 core processor in my desktop computer. For some reason I can access any of the asset files or download quest patcher. Is this because my computer processor is too small? I read that you need at least an i5 to be able to download stuff from github and the discord.

**Comment by Lauriethefish** [comment]
No, it should not be because of a CPU power issue. For future reference, this github is not for support, and is for feature requests and bugs.

**Comment by Lauriethefish** [comment]
Here is a direct link to the [latest release](https://github.com/Lauriethefish/QuestPatcher/releases/tag/2.4.4).
