### ISSUE TITLE
i cant downdload quest patcher

### ISSUE THREAD

**Issue by massileal** [Lauriethefish/QuestPatcher#107]
i recently switched from a laptop to a pc so i wanted to get mods on this game called nox tag (an older version of gtag) and i cant download quest patcher. are you gonna fix that soon?

**Comment by Lauriethefish** [comment]
What do you mean you "can't download it"? Be more specific. What happens when you try to download it?

**Comment by massileal** [comment]
the options to download them don't work

**Comment by Lauriethefish** [comment]
You need to be more specific. What happens when you click the download button?
I can confirm that they DO work.

**Comment by massileal** [comment]
nothing the options are just gray

**Comment by massileal** [comment]
so idk
 if its just me

**Comment by Lauriethefish** [comment]
can you share a screenshot of the buttons you are trying to use

**Comment by massileal** [comment]
alr one sec

**Comment by massileal** [comment]
![image](https://user-images.githubusercontent.com/123216897/213875302-28dcdf01-7813-4876-90c2-1367a0cdc76d.png)

**Comment by massileal** [comment]
idk cuz thats how i used to do it

**Comment by Lauriethefish** [comment]
![image](https://user-images.githubusercontent.com/44222319/213875318-72f42367-361f-4bbd-afee-85fc1d03a1c2.png)

**Comment by massileal** [comment]
do i download mac.dmq?

**Comment by Lauriethefish** [comment]
yes, if you're on mac

**Comment by massileal** [comment]
it shows as a winrar file

**Comment by massileal** [comment]
nvm

**Comment by massileal** [comment]
thanks
