### ISSUE TITLE
Patch app issue

### ISSUE THREAD

**Issue by Kiwi222222** [Lauriethefish/QuestPatcher#109]
When I try and patch Gorilla tag mod I'm getting this message.  Any idea what is wrong?  Also, why does it mention beat saber?
![image](https://user-images.githubusercontent.com/124395183/216716624-c25ff82f-e1ea-47c1-b8c8-33a4b5a28c38.png)

**Comment by Lauriethefish** [comment]
You've enabled the "Disable VR Requirement" option. That option is only intended to work with Beat Saber installations.
