### ISSUE TITLE
Allow to drop urls to qmods on the mods page

### ISSUE THREAD

**Issue by FrozenAlex** [Lauriethefish/QuestPatcher#114]
It wold be a really cool feature that can save one click every time we browse through a modding site or bsmg discord and download a mod. It does require us to download the qmods themselves through the app though. Even though it saves one click, it makes installing mods so much more fun

**Comment by Lauriethefish** [comment]
Implemented in [d2d68d2c96be9d619d7a4908b5314a3db712e659](https://github.com/Lauriethefish/QuestPatcher/commit/d2d68d2c96be9d619d7a4908b5314a3db712e659)
