### ISSUE TITLE
The Possiblity of using multiple mirror urls for ExternalFilesDownloader

### ISSUE THREAD

**Issue by qe201020335** [Lauriethefish/QuestPatcher#117]
While working on the China version of QuestPatcher ([the fork](https://github.com/MicroCBer/QuestPatcher)), I noticed that in the `ExternalFilesDownloader.PrepareDownloadUrls`
https://github.com/Lauriethefish/QuestPatcher/blob/58fa4c5e45194513a0f27cb5ab9db3592247aaff/QuestPatcher.Core/ExternalFilesDownloader.cs#L258-L266
It only takes the first compatible one while the data structure of `file-downloads.json` supports multiple. 

Because of the firewall in China, all download urls need to have a mirror.
So, I'm thinking about making it so that it will construct a `Dictionary<ExternalFileType, HashSet<string>>` with all the compatible `DownloadSet`. Then in the `ExternalFilesDownloader.DownloadFile`, it can take a collection of urls. If one fails, we could simply try another.

If you think this is a great idea, I can implement and pr it to make this an officially supported feature so I don't have to keep hacking around in the fork 😁

**Comment by Lauriethefish** [comment]
Yeah, great idea! Feel free to make a PR and I'll take a look at it.
