### ISSUE TITLE
Never finishes patching step 5/5 "Installing modded APK"

### ISSUE THREAD

**Issue by YorVeX** [Lauriethefish/QuestPatcher#120]
I am trying to patch Beat Saber 1.28, but the last step "Installing Modded APK" is never finished. SideQuest takes 10-15 seconds to install the normal Beat Saber APK, I waited 20 minutes but QuestPatcher just doesn't progress anymore and is probably stuck at this step forever:
![image](https://user-images.githubusercontent.com/528974/230806099-80fad60d-d2c6-4965-9d2f-cda74e339adc.png)

Windows 10 Pro. Installed QuestPatcher through WinGet if that matters.

The log on disk shows these last lines:
```
[2023-04-10 03:15:52 INF] Installing the modded APK . . .
[2023-04-10 03:15:52 DBG] Executing ADB command: adb install "C:\Users\YorVeX\AppData\Local\Temp\QuestPatcher\patching\patched.apk"
```

I can also see that adb is running and holds a lock on this file.

Tried the whole process several times (restarting everything and reinstalling Beat Saber between attempts) but the problem stays the same.

**Comment by YorVeX** [comment]
Tried several times (restarting everything and reinstalling Beat Saber between attempts) but the problem stays the same.

**Comment by YorVeX** [comment]
Killed adb.exe and installed the patched apk file with SideQuest, which took the usual 10-15 seconds and worked fine. Maybe my adb is broken?

**Comment by qe201020335** [comment]
We have seen a similar issue in the Chinese fork that `adb install` sometimes takes forever to finish. Upload the apk then install via `adb pm install` should solve the issue.

We added a config option for this.
```cs
        public async Task InstallApp(string apkPath, bool copyFirst)
        {
            if (copyFirst)
            {
                const string destApkPath = @"/data/local/tmp/tmp.apk";
                await UploadFile(apkPath, destApkPath);
                await RunCommand($"shell pm install {destApkPath}");
            }
            else
            {
                await RunCommand($"install \"{apkPath}\"");
            }
        }
```
https://github.com/MicroCBer/QuestPatcher/blob/da0959b7516c875df1fd7b3b3f3764a2acd8a1ef/QuestPatcher.Core/AndroidDebugBridge.cs#L281-L293

**Comment by Lauriethefish** [comment]
You can also specify `--no-streaming` and ADB will do this for you.
