### ISSUE TITLE
qmod and other files support

### ISSUE THREAD

**Issue by Gamerboy1234567890** [Lauriethefish/QuestPatcher#130]
Just qmod Files? All Mods have DLL files. There Should Be dll support.
If The Devs Can't Add It. Just Close It.

**Comment by qe201020335** [comment]
dll is for pc. qmod is for quest standalone and questpatcher is a tool to manage mods for quest standalone games

**Comment by Gamerboy1234567890** [comment]
Yeah, But I can't Mod Gorilla Tag. All The Mods Are Outdated. What Do I Do About That?

**Comment by Lauriethefish** [comment]
I'm not a gorilla tag modder, but there aren't any mods available for the latest version at the moment.
This site is for QuestPatcher problems. This isn't a problem with QP, so I can't help you any further.
