### ISSUE TITLE
Run it a second time after patching beatsaber error (Quest 3)

### ISSUE THREAD

**Issue by agibson2** [Lauriethefish/QuestPatcher#133]
If you close QuestPatcher and run it again after BeatSaber was already modded (to add more mods to BeatSaber), QuestPatcher stops working and gives the error below when you first launch QuestPatcher.

QuestPatcher.Core.AdbException: chmod: chmod '/sdcard/Android/data/com.beatgames.beatsaber/files/mods/' to 0777: Operation not permitted

If I remove BeatSaber and install 1.28.0 again from scratch, the error does not happen.  It seems to be any launch of QuestPatcher after patching BeatSaber.

EDIT: changed from 1.27.0 to 1.28.0 (typo).

**Comment by Lauriethefish** [comment]
Are you on the quest 3?

**Comment by agibson2** [comment]
Yea.  I thought I said that but I guess not.

**Comment by Lauriethefish** [comment]
Hmm. From the research I did, this seems to be caused by the permissions of the whole file tree being messed up. It will be pretty tricky for me to find the problem, because I don't have a quest 3, but I can try my best.

**Comment by agibson2** [comment]
Maybe it is something that the other version of QuestPatcher is doing (odds seem high if the permissions are being messed up).  I will start from scratch and use this version of QuestPatcher and see if the same thing happens.  Previously I used the other QuestPatcher and then ran this one to see if it had the same error problem whenrunning it after the other QuestPatcher patched things.

**Comment by agibson2** [comment]
I guess it is too early to attempt this version of Quest Patcher with Quest 3.  I get the error below on Quest 3 trying to patch 1.28.0 version of Beat Saber.

System.Exception: Unable to find download URLs suitable for this QuestPatcher version (0.1.0)

**Comment by agibson2** [comment]
Yea.  That QuestPatcher is using a patched libmodloader64.so  instead of the official one which isn't Quest 3 compatible yet.

https://drive.google.com/file/d/1pCPLCe3oSIvy_7uSRKsrm5j154xtOJWh/view?usp=sharing

That was discovered by this reddit post where the person that created that modified QuestPatcher had patched QuestPatcher to use that and also do some permission changes it seems that were required to get it to work.  Seems likely that the new QuestPatcher has extra code causing the issues and maybe not this version.

https://www.reddit.com/r/beatsaber/comments/176v271/how_to_mod_q3/

**Comment by Lauriethefish** [comment]
I'm happy to live chat, it could be very helpful to find what the permission issue is. 

>I think the way the other version works is that it downloads a patched version of something that was fixed for quest 3 so any official download makes since that it might not work yet until other official sources update for Quest 3. I am only installing the core mods, beattogether, and the cosmetics mod which work properly with the patched file.

Correct, it uses a patched version of the modloader that works on Q3. That version isn't officially out yet, so my repository doesn't contain a link to it (I don't want to use a sketchy drive link.)

The new questpatcher doesn't change *much* permission stuff, so it may not be the problem fyi.

**Comment by agibson2** [comment]
No since in wasting anyone's time.  Ill just wait until the official version comes out for libmod...  As you said.  It might not be a problem for the official stuff.

**Comment by ericswpark** [comment]
I encountered the same issue and managed to fix it by deleting the two folders (`libs` and `mods`).

**Comment by Lauriethefish** [comment]
> No since in wasting anyone's time. Ill just wait until the official version comes out for libmod... As you said. It might not be a problem for the official stuff.
Don't worry, you're not wasting my time. If you help me fix the problem, then it helps lots of other people too, so it's worthwhile.

**Comment by Lauriethefish** [comment]
> I encountered the same issue and managed to fix it by deleting the two folders (libs and mods).

Interesting. I could change questpatcher to delete them if the error occurs.

**Comment by ericswpark** [comment]
> Interesting. I could change questpatcher to delete them if the error occurs.

I actually tried `chmod`-ing with just `adb` and found that the directories did not exist at all. So I created them with `mkdir` but QP would still crash. So I deleted them and ran QP one more time and it seemed to work.

**Comment by Lauriethefish** [comment]
> I actually tried chmod-ing with just adb and found that the directories did not exist at all. So I created them with mkdir but QP would still crash. So I deleted them and ran QP one more time and it worked after that.
This should have the same behaviour. Very strange. QP uses ADB, and does the exact same command that I imagine you entered.

**Comment by Lauriethefish** [comment]
https://github.com/Lauriethefish/QuestPatcher/commit/67be6401618ce9f07dc822e438cbcc26629e4f1a introduces the workaround @ericswpark mentioned.
