### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by AgentPickle47** [Lauriethefish/QuestPatcher#134]
After painstakingly redoing the entire process over and over again, it just wouldn't work. I followed all the steps exactly, but as soon as I used Fix Mod Permissions in the tools menu, it worked. Just a suggestion to add it to the README so others don't follow suite.

**Comment by Lauriethefish** [comment]
I think you have filed an issue on the wrong repo. You're looking for https://github.com/timfenton/QuestPatcher.
This repo doesn't have the fixed modloader for quest 3 yet, as it isn't officially out.
