### ISSUE TITLE
Can't mod secondary account

### ISSUE THREAD

**Issue by abboodeno** [Lauriethefish/QuestPatcher#140]
Thank you so much for the patcher, I have meta quest 3, I patched the primary account and mods worked fine,, the issue that I tried so many times to do the same for the secondary account on the same headset but mods wont appear in beatsaber, even if I allow access when it asks for it.

Is there away to fix this ? Am I missing something ?

Thank you for your time

**Comment by abboodeno** [comment]
Thank you for the fast answer, it's sad that bmbf does not work on quest3 and patcher does not support 2 accounts :(

**Comment by Talixme** [comment]
Im new on quest 3 and dont tell me how, but i made it. Do you need some log or something? I'm trying to do it again in another quest 3 but i can replicate the process. I have a pair of quest 3.

**Comment by abboodeno** [comment]
Its amazing if you really did... we are talking about second account on the same device, not on 2 devices

**Comment by Talixme** [comment]
Yep, 2 accounts in one device.
Now im triying to do the same on another quest, i made a backup of everything but doesnt works :(
Can i send you something to give you a clue?
Thanks!!!
