### ISSUE TITLE
[Feature Request] Lemonloader installer?

### ISSUE THREAD

**Issue by lrutjens** [Lauriethefish/QuestPatcher#143]
Any possibility of lemonloader installer support in the future?

**Comment by Lauriethefish** [comment]
IIRC the developers of lemonloader were working on their own installer?

**Comment by lrutjens** [comment]
They have their own installer on android but not for desktop, unless ones in the works rn

**Comment by Lauriethefish** [comment]
I think adding a lemonloader installer is not really within the scope of what questpatcher is meant to offer. But, feel free to create a fork if you want a PC based installer, questpatcher could provide a good base.
