### ISSUE TITLE
QuestPatcher-mac.dmg Not opening

### ISSUE THREAD

**Issue by Ripchub** [Lauriethefish/QuestPatcher#148]
I can't seem to run QuestPatcher-mac.dmg. When I attempt to open it, it says “QuestPatcher” cannot be opened because the developer cannot be verified. When I try to eject the disk image it says The disk image containing “QuestPatcher” could not be ejected. Then it recommends me to move it to the trash immediately. Is there anyway I could bypass this? I'm jus trying to mod beat saber on my quest 3 and questpatcher is the only way I can but it's proving to be difficult when I can't even open it.

**Comment by Ripchub** [comment]
![Image 1-20-24 at 4 12 PM](https://github.com/Lauriethefish/QuestPatcher/assets/157248033/4af93195-dbe8-4289-aeee-b8113568c96e)
![Image 1-20-24 at 4 12 PM (1)](https://github.com/Lauriethefish/QuestPatcher/assets/157248033/ec28a168-e80b-43b8-bb9e-fd1ad8f88abf)

**Comment by qe201020335** [comment]
If you right click on it and then select open, then there should be a button says something like "open anyways" in this pop up.

**Comment by Ripchub** [comment]
THANK YOU SO MUCH
