### ISSUE TITLE
Unable to authenticate oculus account Gorilla Tag

### ISSUE THREAD

**Issue by xelijah3314x** [Lauriethefish/QuestPatcher#151]
Not sure if this is the right place to post this so sorry for wasting your time if it is. When I patch gorilla tag it says that it cannot authenticate my account so I was wondering if that was just something that happens when you have a dev version of the game or if there is something that I'm doing wrong. Thanks in advance 👋

**Comment by Lauriethefish** [comment]
That's normal behavior - you would need to make some kind of mod for gorilla tag to disable authentication by using a different server. Then you could use the patched version.
