### ISSUE TITLE
Upgrading a mod removes all dependencies

### ISSUE THREAD

**Issue by kodenamekrak** [Lauriethefish/QuestPatcher#153]
When installing an updated version of a mod which is already installed, dependencies are still removed which is quite annoying.

For example, i have custom types 0.16.17 installed, when I install 0.16.18 it first removes 0.16.17 which removes all mods that depend on it. It would be nice if questpatcher could handle mod upgrades differently

**Comment by Lauriethefish** [comment]
No longer reproducible on latest - seems to have been fixed.
