### ISSUE TITLE
Questpatcher Closing After "Loading"

### ISSUE THREAD

**Issue by beehive-git** [Lauriethefish/QuestPatcher#154]
Immediately as it finishes the screen where it says "QuestPatcher Loading.." it just closes and does nothing. I'm on Windows 11 trying to install it on my Quest 3 if that helps. It worked once, but it crashed almost immediately. I have attached the screen I'm talking about 
![image](https://github.com/Lauriethefish/QuestPatcher/assets/160347653/c1709168-820c-4b4e-aebc-d7022c6dc230)
Update: It seems to only crash when I'm actively in the tab. This error message also pops up occasionally when trying to start it up 
![image](https://github.com/Lauriethefish/QuestPatcher/assets/160347653/8518ebd4-f0c9-4aa8-91f5-77ad154dbff8)

**Comment by Lauriethefish** [comment]
This problem happens when a program is trying to access QuestPatcher files, often when QP was restarted during the installation process.
Restarting your computer will fix it.
