### ISSUE TITLE
Mods not showing in QP

### ISSUE THREAD

**Issue by reallycoo1** [Lauriethefish/QuestPatcher#158]
So I've managed to get it to the point where QP is loaded up, but there are no mods showing for me to select. I tried changing Tthe app to something else and then back to beat sabre. But it never allows me to Use quest loader. When I click on re patch my app, it does. it , but yet there's still nothing there to select.

**Comment by gilturia** [comment]
i have the same problem

**Comment by qe201020335** [comment]
You need to actually install some mods in order for them to show up.
If you don't see any mods, that mean there aren't any mods installed

**Comment by reallycoo1** [comment]
Laurie! Hello!
No, I can't even see how to even get to  install them? The window  is just empty?
________________________________

**Comment by qe201020335** [comment]
@reallycoo1 I am not Laurie but here is a site for beat saber quest mods https://computerelite.github.io/tools/Beat_Saber/questmods.html

**Comment by gilturia** [comment]
thank you i didn't know that we have to download the mods

 i download them and i entered the game but its pitch black i cant enter the game is there a reason for that?

**Comment by qe201020335** [comment]
@gilturia 
You can go to the BSMG discord for support on modding the game
discord.gg/beatsabermods
