### ISSUE TITLE
QuestPatcher not open

### ISSUE THREAD

**Issue by Mythalize** [Lauriethefish/QuestPatcher#17]
When I downloaded QuestPatcher, it downloaded but it wouldn't open. Can I get help?

**Comment by Lauriethefish** [comment]
Do not ask for support here - ask in the gorilla tag modding discord instead.

**Comment by Mythalize** [comment]
Thanks

**Comment by LunaChipp** [comment]
it wont open for me and i dont have discord how do you fix it
