### ISSUE TITLE
Add manifest workaround for MRC (mixed reality capture)

### ISSUE THREAD

**Issue by ElDavoo** [Lauriethefish/QuestPatcher#174]
With the v60 update, Meta broke all apps using MRC (Mixed Reality Capture, in other words third-person view that gets sent over TCP to a PC). This is because this block is now needed inside AndroidManifest.xml (inside an `<application>` block):
```
<uses-native-library
                android:name="libOVRMrcLib.oculus.so"
                android:required="true" />
```
I'd argue that `android:required="false"` can be safely set. In this way, the app won't break if this library ceases to exist for some reason.  
Since now this application is the de-facto standard for modding (especially Beat Saber), and since this is done by decompiling, modding, recompiling, signing and installing the APK, I would add this capability to QuestPatcher.

**Comment by Lauriethefish** [comment]
Is this still a useful addition?

**Comment by ElDavoo** [comment]
Not much, as people wanting  MRC usually use the PCVR version of the game, but I thought that this enhancement wouldn't be much code to be written.

**Comment by Lauriethefish** [comment]
okay if it still does something I might add it soon

**Comment by ElDavoo** [comment]
> it still does something

Yes, I tried it and it works, but doing it manually (e.g. decompiling, recompiling the apk and especially resigning it) is far more inaccessible and incompatible with modding solutions (mainly because of different signatures)

**Comment by Lauriethefish** [comment]
Workaround is now implemented in QuestPatcher. It's disabled by default but you can turn it on in the `Patching Permissions` menu.
