### ISSUE TITLE
[Feature Request] Mod lower beat saber versions than 1.35

### ISSUE THREAD

**Issue by jessicaengel451** [Lauriethefish/QuestPatcher#175]
I would like to mod beat saber 1.28 since the [Oculus OS update broke permissions](https://github.com/ComputerElite/QuestAppVersionSwitcher/issues/59). Could modding other versions please be added?

**Comment by Lauriethefish** [comment]
QuestPatcher supports modding 1.28 already. It does not support the downgrading process, you will need to use QAVS to downgrade and then QP to mod. Downgrading is not what QP is designed to do so I will not consider that as a feature request.

**Comment by jessicaengel451** [comment]
that was a fast response! I didn't  know that. Thanks for letting me know and all that you do! the haptics in the new update are driving me crazy.
