### ISSUE TITLE
Do not fail startup if getting full path to invoked ADB fails

### ISSUE THREAD

**Issue by d3gjay** [Lauriethefish/QuestPatcher#179]
![Screenshot 2024-05-11 163020](https://github.com/Lauriethefish/QuestPatcher/assets/153825786/630480ba-ae45-4b6d-94f8-c8e29394ad9a)

i have no idea what this is and cant find anything about it anywhere

**Comment by qe201020335** [comment]
A quick Google search tells me it may be caused by antivirus.

**Comment by Lauriethefish** [comment]
The property that's being read here is not strictly needed for QuestPatcher to function, so it would make sense that in the case that reading it fails, we'd disable the functionality that needs it (which in this case relates to the detection of ADB daemons).

Changing this issue accordingly.
