### ISSUE TITLE
Patching failed on Signing APK

### ISSUE THREAD

**Issue by leovic0101** [Lauriethefish/QuestPatcher#18]
I installed the latest QuestPatcher release (2.1.0) and when I start patching, it threw an unknown exception. 
Below is the error message:

Signing APK (this might take a while) . . .
Patching failed!: QuestPatcher.Core.Patching.PatchingException: Signed APK (/var/folders/n2/0g2x1_md08n4srhsdkxd9kv00000gn/T/QuestPatcher/patching/patched-aligned-debugSigned.apk) not found! Signing must have failed
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/Patching/PatchingManager.cs:line 401
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher/ViewModels/PatchingViewModel.cs:line 59

Not sure where I can find the signed APK though. 

Below is the screenshot of the error

![Screen Shot 2021-06-24 at 8 18 49 PM](https://user-images.githubusercontent.com/4494502/123350653-6df3c600-d529-11eb-8ccc-9def2c05956f.png)

Any help is most appreciated.

Thanks.

**Comment by Lauriethefish** [comment]
This problem is an error within the APK signer that I cannot track down.

**Comment by leovic0101** [comment]
Thanks @Lauriethefish for looking into it.
Is there any pre-reqs or system requirements that we need to do prior to patching? 
I am running it on the latest MacOS. 
Thanks.

**Comment by leovic0101** [comment]
Also I looked at the

**Comment by leovic0101** [comment]
Sorry.
Mistakenly closed this issue

**Comment by wjake35** [comment]
I am having the same problem

**Comment by Lauriethefish** [comment]
I am aware that many people have this problem.
Please refrain from commenting about you having the same issue.

**Comment by Lauriethefish** [comment]
@leovic0101 No, there aren't any pre-requisites. The signer sometimes just doesn't work.
In the next update I will pass the `--debug` flag to get more info.

**Comment by Lauriethefish** [comment]
Latest actions build passes this flag. Please try it @leovic0101 and send your logs for additional debugging information.
https://github.com/Lauriethefish/QuestPatcher/actions/runs/974082261

**Comment by leovic0101** [comment]
Thanks, @Lauriethefish .

Please see log.
[log.log](https://github.com/Lauriethefish/QuestPatcher/files/6720313/log.log)

**Comment by Lauriethefish** [comment]
@leovic0101.
Try running the command `rm -r /var/folders/0z/n3yg93qs2tsb20hv8yws4pyr0000gn/T/uapksigner-13392142673826160410/` in your terminal and see if that helps.

**Comment by leovic0101** [comment]
@Lauriethefish  file does not exists in my machine.

**Comment by leovic0101** [comment]
I am attaching a fresh set of logs. I also enabled ADB logging just in case you need it.
[adb.log](https://github.com/Lauriethefish/QuestPatcher/files/6720342/adb.log)
[log.log](https://github.com/Lauriethefish/QuestPatcher/files/6720343/log.log)

**Comment by Lauriethefish** [comment]
Try this build: https://github.com/Lauriethefish/QuestPatcher/actions/runs/974482205

**Comment by Lauriethefish** [comment]
Hold on, that build won't work. Give me a minute.

**Comment by Lauriethefish** [comment]
Try this build once it finishes: https://github.com/Lauriethefish/QuestPatcher/actions/runs/974485970

**Comment by leovic0101** [comment]
It worked! I was able to finish the patch. 

Thanks!

**Comment by Lauriethefish** [comment]
@leovic0101 Once the latest build [here](https://github.com/Lauriethefish/QuestPatcher/actions/runs/974574679) finishes, could you test that as well?
It should say `Signing the APK failed with zipalign enabled. Falling back to non-zipalign . . .` for you when signing.

**Comment by leovic0101** [comment]
sure. will do.

**Comment by leovic0101** [comment]
Confirming that I got the message and was able to run the patch with no errors.
Thanks again for fixing.

**Comment by Lauriethefish** [comment]
Nice, I will release this fix soon-ish.
