### ISSUE TITLE
Previous 'crash upon start when headset connected' issue fixed?

### ISSUE THREAD

**Issue by Lank01** [Lauriethefish/QuestPatcher#189]
I have worked with questpatcher in the past, just with gorilla tag instead. I have seen another issue like mine that went into greater detail than i think will have to with this issue. But now, whenever i have my quest connected via airlink, i am unable to start questpatcher. Could airlink be the problem? I am unsure, but i don't think so. Please correct me if im wrong because i have no issue ordering a thing or two for wired link.

**Comment by qe201020335** [comment]
When using AirLink, there is no adb connection unless you still have a usb connection or you have hacked around in your quest and enabled wireless adb. Therefore there is probably no point to use QuestPatcher regardless whether it crashes or not. 

That being said, QuestPatcher should not just crash. There is definitely a problem somewhere. Assuming you are on Windows, can you try running QuestPatcher with admin?

**Comment by Lauriethefish** [comment]
Questpatcher does not and is not intended to work with airlink. You need a usb cable or to set up wireless adb. Closing as this is not a clear bug.
