### ISSUE TITLE
Quest patcher doesnt mod beat saber 

### ISSUE THREAD

**Issue by Overghan** [Lauriethefish/QuestPatcher#199]
Quest patcher says everything went fine and it is modded but the mods dont show up in Beat saber

**Comment by qe201020335** [comment]
Have you actually installed any mods?

**Comment by Lauriethefish** [comment]
This means that you either didn't install any mods and only patched the game, or you're using the game on a secondary account (which isn't supported by the beat saber modding community), or you've got mods installed for the wrong version of the game.

It is not a bug with questpatcher, therefore I will be closing this issue.
