### ISSUE TITLE
32-bit versions

### ISSUE THREAD

**Issue by AltF420** [Lauriethefish/QuestPatcher#27]
If you can, make a 32-bit version for Ubuntu.

**Comment by Lauriethefish** [comment]
There are an insufficient 32 bit users to warrant a 32 bit ubuntu version. I already release 4 different versions of QuestPatcher on every release.

**Comment by Lauriethefish** [comment]
You could almost certainly clone it and look into building for 32 bit yourself though. It's just a .NET core application.

**Comment by AltF420** [comment]
Okay then, I will try. I will close the threads if I am able to do that. Thanks!

**Comment by Lauriethefish** [comment]
Don't worry - I've already closed the issue.

**Comment by AltF420** [comment]
Okay
