### ISSUE TITLE
Cannot choose game to patch

### ISSUE THREAD

**Issue by MintFreezeyt** [Lauriethefish/QuestPatcher#46]
So I heard that you can use quest patcher for modding beat saber and I have the right version of beat saber and quest patcher but it won't allow me to press on any games and my developer mode on so I don't think it is that I tried plugging my quest into a different port and then using it still didn't work and when I go to side quest it shows that my quest is plugged in so I just don't know what to do anymore.

**Comment by Lauriethefish** [comment]
Please be more specific as to how it "won't allow me to press on any games".

**Comment by MintFreezeyt** [comment]
I'll have to get a picture when I get home since I don't know how to explain it to much

**Comment by Lauriethefish** [comment]
Too long with no information, closing.
