### ISSUE TITLE
Quest Patcher Mac - Quit Unexpectedly On Open

### ISSUE THREAD

**Issue by KaiSimpson13123** [Lauriethefish/QuestPatcher#49]
When I try to open QuestPatcher I get an error saying "QuestPatcher Quit Unexpectedly"

**Comment by TitoBurr** [comment]
Yes me too and it seems others have this problem as well. I follow all the steps and every time I open the application it say "QuestPatcher Quit Unexpectedly". I have tried uninstalling and reinstalling 6 times now and it does not work. Please Try to fix this I will check everyday to see if you get back at me, Thank you.

**Comment by midnight12346** [comment]
i am also not able to open it

**Comment by Lauriethefish** [comment]
Is your mac using an M1 architecture?

**Comment by PoorDoor** [comment]
i have an m1 macbook pro and im started to wonder if it wont open because of m1

**Comment by higuyswd** [comment]
What is your estimated time this gonna be fixed?

**Comment by Lauriethefish** [comment]
To be honest, I'm not entirely interested in fixing it, mostly because I don't have a mac VM so it's very hard to test, but also because I'm not really a big fan of apple and their products.

**Comment by Lauriethefish** [comment]
Fixed in version 2.4.3
