### ISSUE TITLE
Feature Req: Copy over the data from /sdcard/Android/data/appid/files

### ISSUE THREAD

**Issue by RedBrumbler** [Lauriethefish/QuestPatcher#50]
On patch, the data from there should be copied over in case there is data there that should carry over to a modded install, maybe even offer backup functionality for that where if you uninstall with questpatcher you can keep a backup of the data there?

**Comment by Lauriethefish** [comment]
Important to note that for the second request, QP will be needed to restore the backup. This is because reinstalling an APK will overwrite the `/sdcard/Android/data/my.package.id/files` directory in most cases.
