### ISSUE TITLE
Quest Patcher To Many Devices is there a Fix?

### ISSUE THREAD

**Issue by MrMukky** [Lauriethefish/QuestPatcher#65]
@Lauriethefish Is there a fix to this bug because im trying get the app working for when mods come back out!?

**Comment by Lauriethefish** [comment]
It's not a bug, you need to remove any emulators that you currently have running. This issues section is for bugs only, so I'm gonna have to close this,

**Comment by XboxGitHub** [comment]
![Screenshot (157)](https://user-images.githubusercontent.com/67390048/189460622-960688d2-a28b-4e75-9a60-0c60908a7c97.png)
Why does it say that when I try to activate computer mods

**Comment by XboxGitHub** [comment]
and it's always a beat saber mod, when i delete it, it just keeps popping up in the files
