### ISSUE TITLE
I used it on gorilla tag, but now it says it cannot authentic my oculus account

### ISSUE THREAD

**Issue by Bannanaboii11** [Lauriethefish/QuestPatcher#71]
I've tried leaving and rejoining. What should I do?

**Comment by Lauriethefish** [comment]
Uninstall gorilla tag in the tools tab of QuestPatcher and reinstall vanilla gorilla tag.
Gorilla tag mods are not available at the moment.

**Comment by Bannanaboii11** [comment]
Thank you
