### ISSUE TITLE
QuestPatcher keeps crashing

### ISSUE THREAD

**Issue by Yak9T** [Lauriethefish/QuestPatcher#8]
I downloaded the Patcher and every time I open it. it makes it to the checking to see if its modded but then it crashes afterwards I redownloaded the thing and it still keeps crashing. I have no clue on what to do so if you could help that would be great

**Comment by Lauriethefish** [comment]
Please go to `%appdata%/QuestPatcher` and paste the contents into here: https://paste.md-5.net/
Then save it and share the link here.

**Comment by Lauriethefish** [comment]
Gonna close this due to no response.
In the future, please use `#installation-help` in the Gorilla Tag modding discord.
