### ISSUE TITLE
"Multiple android devices plugged in at once" 

### ISSUE THREAD

**Issue by Grapes1532** [Lauriethefish/QuestPatcher#84]
I unplug my quest "Your quest is in offline mode"
I plug it in "Multiple android devices plugged in at once"
I've literally got everything unplugged, im on my laptop, i dont have bluestacks or any android emulator, so why is this happening?

**Comment by Lauriethefish** [comment]
Could you send the output of `adb devices` here please?

**Comment by Lauriethefish** [comment]
Closing due to lack of response
