### ISSUE TITLE
Crash on start on mac

### ISSUE THREAD

**Issue by hiwhdge** [Lauriethefish/QuestPatcher#88]
i keep trying to open quest patcher and it says its damaged and cant be opened

**Comment by Lauriethefish** [comment]
What model of mac do you have?

**Comment by hiwhdge** [comment]
macos catalina

**Comment by Lauriethefish** [comment]
No, not your OS. What mac do you have?

**Comment by hiwhdge** [comment]
trying to find where it says that

**Comment by hiwhdge** [comment]
Imac 21.5-inch late 2013

**Comment by Lauriethefish** [comment]
Duplicate of #49
