### ISSUE TITLE
Questpatcher (Mac) Error

### ISSUE THREAD

**Issue by DarkknightSide** [Lauriethefish/QuestPatcher#90]
If I Start Quest Patcher there is always an error that says File is damaged. 
I Reinstalled it multiple times Sadly it still didn't work 
I use a Mac mini (M1, 2020) and I use version macOS Monterey 12.5 
Thank you for reading this
have a nice day

**Comment by PoorDoor** [comment]
im having the same issue on my Macbook pro (Also M1) maybe its because of the m1 chip?

**Comment by DarkknightSide** [comment]
Probably

**Comment by Lauriethefish** [comment]
Duplicate of #49
