### ISSUE TITLE
Change the git hub link for Monke Computer Activator

### ISSUE THREAD

**Issue by XboxGitHub** [Lauriethefish/QuestPatcher#92]
The RedBrumbler MonkeComputer GitHub link isn't there anymore
Add this one: https://github.com/GalaxyOnVR/MonkeComputer
![Screenshot (165)](https://user-images.githubusercontent.com/67390048/192162089-2eddd816-9065-471e-81ff-f5cad57aa120.png)

**Comment by Lauriethefish** [comment]
This is an issue with the QMOD file you are installing, and is not an issue with QuestPatcher. Please ask the author of the mod to change the link.
